services:
  app:
    image: 'parabol-selfhosted:latest'
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    restart: always
    environment:
      - SERVICE_FQDN_APP_3000
      - 'APP_ORIGIN=${SERVICE_URL_APP}'
      - SERVER_ID=1
      - 'SERVER_SECRET=${SERVICE_PASSWORD_SECRET}'
      - IS_ENTERPRISE=true
      - FILE_STORE_PROVIDER=local
      - PROXY_CDN=false
      - MAIL_PROVIDER=debug
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=pgparaboladmin
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - POSTGRES_DB=parabol-saas
      - POSTGRES_USE_PGVECTOR=true
      - 'REDIS_URL=redis://valkey:6379'
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_started
  postgres:
    image: 'pgvector/pgvector:0.8.0-pg16'
    restart: always
    environment:
      - POSTGRES_USER=pgparaboladmin
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - POSTGRES_DB=parabol-saas
    volumes:
      - 'parabol-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pgparaboladmin -d parabol-saas']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
  valkey:
    image: 'valkey/valkey:9.0-alpine'
    restart: always
    command: 'valkey-server --save ""'
    volumes:
      - 'parabol-valkey-data:/data'
volumes:
  parabol-postgres-data: null
  parabol-valkey-data: null
